### ISSUE TITLE
Never exits

### ISSUE THREAD

**Issue by briannesbitt** [greenlaw110/Rythm#170]
I started testing out the Rythm engine tonight.  I am initially interested in getting the hot reload working so I was trying it with "engine.mode" set to "dev".

The following sample program doesn't ever exit:

```java
import org.rythmengine.RythmEngine;

import java.util.HashMap;
import java.util.Map;

public class RythmTest
{
   public static void main(String... args) throws Exception {
      Map<String, Object> config = new HashMap<String, Object>();

      config.put("engine.mode", "dev");
      config.put("home.template.dir", "z:/dev/Rythm/src/main/java/templates");

      final RythmEngine engine = new RythmEngine(config);

      WL("Prod Mode:" + engine.isProdMode());
      WL(engine.render("my.html", "brian N"));
   }

   public static void WL(String s) {
      System.out.println(s);
   }
}
```

The following sample program does quit as expected (notice the engine.mode)

```java
import org.rythmengine.RythmEngine;

import java.util.HashMap;
import java.util.Map;

public class RythmTest
{
   public static void main(String... args) throws Exception {
      Map<String, Object> config = new HashMap<String, Object>();

      config.put("engine.mode", "prod");
      config.put("home.template.dir", "z:/dev/Rythm/src/main/java/templates");

      final RythmEngine engine = new RythmEngine(config);

      WL("Prod Mode:" + engine.isProdMode());
      WL(engine.render("my.html", "brian N"));
   }

   public static void WL(String s) {
      System.out.println(s);
   }
}
```

**Comment by fpoliquin** [comment]
I agree with briannesbitt; you should remove completely the shutdown hook and set deamon threads. This would avoid a memory leak. See: https://github.com/greenlaw110/Rythm/issues/243

**Comment by greenlaw110** [comment]
The issue is actually in the `EhCacheService`, which starts a non-daemon thread in default configuration. Now Rythm will load the concurrent map based `SimpleCacheService` by default. So the system should be able to shutdown in dev mode without calling `RythmEngine.shutdown` explicitly in default configuration. See https://github.com/greenlaw110/Rythm/blob/master/src/test/java/org/rythmengine/issue/GhIssueTest.java#L246
