### ISSUE TITLE
Dev mode hot reload - understanding.

### ISSUE THREAD

**Issue by briannesbitt** [greenlaw110/Rythm#174]
I am trying to get the hot reload working in dev mode.  Here is my simple test:

```java
public class RythmTest
{
   public static void main(String... args) throws Exception {
      Map<String, Object> conf = new HashMap<String, Object>();
      conf.put("engine.mode", "dev");
      conf.put("home.template", new File("z:/dev/Rythm/src/main/resources/templates"));

      RythmEngine engine = new RythmEngine(conf);

      for (int i = 0 ; i < 5 ; i++) {
         Thread.sleep(2000);
         WL(engine.render("helloworld.html", "Brian Nesbitt"));
      }
   }
   public static void WL(String s) {
      System.out.println(s);
   }
}
```

While the thread is sleeping I change the `helloworld.html` file and add some text.  I would expect the engine would see that the file has changed and reload the file on the next render call.  This doesn't happen.

**Comment by greenlaw110** [comment]
Fixed by adding "resource.refresh.interval" configuration. Unit test case: https://github.com/greenlaw110/Rythm/blob/master/src/test/java/org/rythmengine/issue/GhIssueTest.java#L261. See also https://github.com/greenlaw110/Rythm/blob/master/src/test/java/org/rythmengine/issue/Gh174Helper.java
