### ISSUE TITLE
Inconsisteny while passing arguments to base template via @extends

### ISSUE THREAD

**Issue by sojin** [greenlaw110/Rythm#197]
Hi,
I've a base template layout.html, something like

```
@args String pageTitle 
...
<title>@pageTitle</title>
...
@doLayout()
...
```

I'm extending this template in multiple child template as follows:

in page1.html

```
@extends(layout, pageTitle:"page1")
```

in page2.html
```
@extends(layout, pageTitle:"page2")
```

it works most of the time, but I've noticed that the title is getting overriden occasionally, ie. page2.html gets 'page1' as title and vice versa.

But I haven't noticed such behaviour if I use @set and @get.

Any idea?

**Comment by greenlaw110** [comment]
I am pretty sure this issue has been fixed. Close the issue as no response from requester for long time
