### ISSUE TITLE
Failed invocation after template reload in dev mode

### ISSUE THREAD

**Issue by bushed** [greenlaw110/Rythm#239]
Hi! I use v 1.0.1. Here is my project tree:
template/main.rythm
invocable/another.rythm

in 'main.rythm' I invoke another template: 
`@invocable.another({
    param : "value"
})`

Now everything work fine. But if I made some changes in 'main.rythm' and try to render it again I got an exception:
:warning: `org.rythmengine.exception.RythmException: cannot find tag: path.to.my.templates.invocable.another.rythm`

I found that after `RythmEngine::restart()` call, `_templates` Map doesn't contains invocable tags. Besides, resource loader instead of `invocable.another` now trying to load `path.to.my.templates.invocable.another` and then this method look in folder somewhere like: `/path/to/my/templates/path/to/my/templates/invocable/another.rythm`

I have to catch `RythmException`, delete *__R_T_C__* files, instantiate new engine and only then it will work.

**Comment by greenlaw110** [comment]
Fixed. Try the 1.1.1-SNAPSHOT version
