### ISSUE TITLE
Compiler uses 1.5 source compilance if running on Java 8

### ISSUE THREAD

**Issue by bblonski** [greenlaw110/Rythm#240]
I upgraded to Java 8 and had my templates break because they required java source level 1.7 or greater.  It looks like the java version is automatically detected by the internal compiler, but java.version 1.8 is specifically commented out and defaults to source level 1.5.  Is there a reason support for source level 1.8 is disabled?  Can we at least default to source 1.7 if on java 1.8?

**Comment by greenlaw110** [comment]
Try the latest 1.1.1-SNAPSHOT version.
