### ISSUE TITLE
Can't use "home.template" with servlet 3.0 

### ISSUE THREAD

**Issue by DheerendraRathor** [greenlaw110/Rythm#241]
rythm does not seem to detect templates from configured in `Rythm.init()` by a HashMap in servlet 3.0

Please refer to [this question](http://stackoverflow.com/questions/26494075/unable-to-use-rythm-template-engine-with-servlet-3-0) on stackoverflow.

**Comment by greenlaw110** [comment]
Not an issue. As you are using rythm's built-in resource manager, it delegate the resource loading to `Thread.currentThread.getContextClassLoader()`, which can not load any resources under `webapp` folder. See http://stackoverflow.com/questions/8749969/resolving-the-root-of-a-webapp-from-getresource. 

If you want to load templates under `webapp` folder, you need to create your own resource manager and delegate to `ServletContext` to load template. 

Fortunately you don't need to do that. Just put your templates under `resources` folder and then it will just work as expected. Here is a simple project proved it:

![image](https://cloud.githubusercontent.com/assets/216930/6980535/10bc162c-da3f-11e4-8b58-a4349529906b.png)

The project source code can be found at https://github.com/greenlaw110/rythm-gh-issue-241
