### ISSUE TITLE
Get list of declared arguments for template

### ISSUE THREAD

**Issue by jjlauer** [greenlaw110/Rythm#245]
Hi,

I've been digging thru the project for a couple hours trying to figure out a way to get the list of declared arguments for a template.  For example, if the template declares this:

```java
@args models.User user, models.Order order
```

Then I'm hoping I could do something like:

```java
Map<String,Class> declaredArgs = Rythm.engine().getTemplate("template").getDeclaredArgs();
```

Which is an ordered map (e.g. LinkedHashMap) of the argument names and classes that the template requires.

Is there a way to do this with the latest version?  If not, would it be easy to add.  If you are unable to do it, could you point me in the direction to add it myself?

Thx.

Joe

**Comment by greenlaw110** [comment]
Rythm template does not support get declared args. However there is a protected member named `__renderArgs` declared as:

```java
/**
 * Stores render args of this template. The generated template source code
 * will also declare render args as separate protected field while keeping
 * a copy inside this Map data structure
 */
protected Map<String, Object> __renderArgs = new HashMap<String, Object>();
```

You can easily write a utility method to fetch it by using reflection. However the order of declaration is not kept by the hash map. If you are okay to build a customized Rythm, you can change the `org.rythmengine.template.TemplateBase` by using `LinkedHashMap` to replace the `HashMap`, you can even add a public method to allow your other code to fetch it

**Comment by jjlauer** [comment]
So I was able to figure out how to do this -- you helped point me in the right direction.  However, I was curious if you had any suggestions for what I'm trying to do.  I'm hoping to take the @args in a template, parse it, and generate Java source that generates a type-specific render() method so that I can let the Java compiler statically check the type.  The problem I'm running into is that it looks like the default parser attempts to resolve Java types -- which leads to a chicken egg problem.  Here is the pattern that I was hoping to do:

1. Parse all template sample.rythm. Java types for @args not resolved during parsing. Let's say the template starts with this:

@args com.sample.Foo foo, com.sample.Bar bar

2. Source code generated for each template that creates a method that includes the types for each argument.  Maybe something like template.sample.java

public class sample {
  static public String render(com.sample.Foo foo, com.sample.Bar bar) {
    Map<String,Object> args = new HashMap<String,Object>();
    args.put("foo", foo);
    args.put("bar", bar);
    return Rythm.render("sample.rythm", args);
  }
}

3. Include generated source code along with application code to be compiled all at the same time.

The benefit is that if arguments change to a template -- they will be caught at compile time rather than runtime.

Is this doable?  If it isn't, do you think Rythm can be tweaked to make it work?  Do you think I should just write my own simple parser for step #1 and then rely on Rythm for the rest?  Since we have a chicken/egg dilemma, the initial parsing without trying to resolve types is critical.

**Comment by jjlauer** [comment]
After taking another look after a short break, I figured it out. CodeBuilder seems to offer exactly what I was looking for.
