### ISSUE TITLE
org.rythmengine.exception.CompileException: SomeClass cannot be resolved to a type

### ISSUE THREAD

**Issue by WolfgangFahl** [greenlaw110/Rythm#252]
```
 @Test
  public void testLocalClassAsDefParam() {
    String template = "@{ class SomeClass {\n" + "  String someField;\n"
        + "}\n" + "SomeClass someInstance=new SomeClass();\n"
        + "someInstance.someField=\"someValue\" \n" + "}\n"
        + "@def func(SomeClass c) {\n" + "@c.someValue\n" + "}\n"
        + "@func(someInstance)\n";
    String result = Rythm.render(template, "noargs");
    check("someValue", result);
  }
```

```
org.rythmengine.exception.CompileException: SomeClass cannot be resolved to a type

Template: 
@{ class SomeClass {
  String someField;
}
SomeClass someInstance=new SomeClass();
someInstance.someField="someValue" 
}
@def func(SomeClass c) {
@c.someField
}
@func(someInstance)


Relevant template source lines:
-------------------------------------------------
   1: @{ class SomeClass {
   2:   String someField;
   3: }
   4: SomeClass someInstance=new SomeClass();
   5: someInstance.someField="someValue" 
   6: }
   7: @def func(SomeClass c) {
   8: @c.someField
   9: }
   10: @func(someInstance)


Relevant Java source lines:
-------------------------------------------------
   37: 		if(0 == __pos) __setRenderArg("arg", __arg);
   38: 		return this;
   39: 	}
   40: 
   41: 
>> 42: public org.rythmengine.utils.RawData func(SomeClass c){
   43: org.rythmengine.template.TemplateBase oldParent = this.__parent;
   44: try{
   45: this.__parent = this;
   46: StringBuilder __sb = this.getSelfOut();this.setSelfOut(new StringBuilder()); //line: 8
   47: 
   48: try{pe(c.someField);} catch (RuntimeException e) {__handleTemplateExecutionException(e);}  //line: 8
```

**Comment by greenlaw110** [comment]
Well I wouldn't expect that complicated usage scenario. Can't see the necessary to allow people defining a class in a template.

**Comment by WolfgangFahl** [comment]
Oh - this is the main feature I am currently using for Rythm and its Unique Position in the market which could be much improved adding this functionality.

**Comment by greenlaw110** [comment]
`SomeClass` is actually a inner class inside a class method `build`, while `@def` is to declare another class method, which obviously doesn't have the access to a class that is declared inside `build` method. However you can still declare class in the template and access it's properties and methods. Here is an live example:

http://fiddle.rythmengine.org/#/editor/e541590b38284d23926c35e13f5db667

**Comment by WolfgangFahl** [comment]
Hello Green,

thank you for your response and showing me the limits of Rythm with your
fiddle.Let's discuss the details next weekend - I am looking forward to
chatting with you.

Wolfgang

Am 31.03.15 um 02:45 schrieb Green Luo:
>
> |SomeClass| is actually a inner class inside a class method |build|,
> while |@def| is to declare another class method, which obviously
> doesn't have the access to a class that is declared inside |build|
> method. However you can still declare class in the template and access
> it's properties and methods. Here is an live example:
>
> http://fiddle.rythmengine.org/#/editor/e541590b38284d23926c35e13f5db667
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenlaw110/Rythm/issues/252#issuecomment-87888612>.
>

-- 

BITPlan - smart solutions
Wolfgang Fahl
Pater-Delp-Str. 1, D-47877 Willich Schiefbahn
Tel. +49 2154 811-480, Fax +49 2154 811-481
Web: http://www.bitplan.de
BITPlan GmbH, Willich - HRB 6820 Krefeld, Steuer-Nr.: 10258040548, Geschäftsführer: Wolfgang Fahl
