### ISSUE TITLE
How to escape {

### ISSUE THREAD

**Issue by WolfgangFahl** [greenlaw110/Rythm#253]
as a workaround for #252 i am trying to split my functions - but there is a follow up problem.

```
@def startblock {
  starting a block {
}
@def endblock {
   } ending a block
}
```

won't work - how to escape the `{` and `}` for the start and end of the blocks that are to be output and not part of Rythm input?

**Comment by WolfgangFahl** [comment]
@("{") 
and
@("}")

is a useable workaround

**Comment by greenlaw110** [comment]
Well done! I would say you know about Rythm than me ;-)

**Comment by greenlaw110** [comment]
Issue moved to https://github.com/greenlaw110/rythm-doc/issues/31
