### ISSUE TITLE
@ignored if blank is missing

### ISSUE THREAD

**Issue by WolfgangFahl** [greenlaw110/Rythm#254]
```
@args Bar bar, String s
@{
  class SomeClass {
    String someField;
    public String getValue() {
       return someField;
    }
  }
  SomeClass someClass=new SomeClass();
  someClass.someField="testValue";
}
@bar@someClass.getValue()@s
```

When Json Input is:

```
{"bar": {"id": "ABCD"}, "s": "abcd"}
```

Expected:

```
Bar[ABCD]testValueabcd
```

Is:

```
Bar[ABCD]someClass.getValue()abcd
```

`@bar @someClass.getValue() @s` produces a much better output but has superfluous unwanted blanks ...

**Comment by greenlaw110** [comment]
Try this:

```
@(bar)@(someClass.getValue())@s
```

**Comment by WolfgangFahl** [comment]
Thanx- this works and I am using it heavily now.

Am 30.03.15 um 05:16 schrieb Green Luo:
>
> Try this:
>
> |@(bar)@(someClass.getValue())@s
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenlaw110/Rythm/issues/254#issuecomment-87528240>.
>

-- 

BITPlan - smart solutions
Wolfgang Fahl
Pater-Delp-Str. 1, D-47877 Willich Schiefbahn
Tel. +49 2154 811-480, Fax +49 2154 811-481
Web: http://www.bitplan.de
BITPlan GmbH, Willich - HRB 6820 Krefeld, Steuer-Nr.: 10258040548, Geschäftsführer: Wolfgang Fahl
