### ISSUE TITLE
Variables in default area of @render are not updated

### ISSUE THREAD

**Issue by chocstarfish** [greenlaw110/Rythm#255]
In my master page I have something like this:
```
@args String current
@current
@render("sidebar"){
    @current
}
```
The html renders two different values when I use two sub-pages 
Subpage1
```
@extends(layout.main, current:"value1")
```
Subpage2
```
@extends(layout.main, current:"value2")
```
to override the variable defined in the master page.

That is to say when I navigate to Subpage 2 after visiting Subpage1, the value of "current" is not updated in the default area of siderbar.

**Comment by greenlaw110** [comment]
What's your rythmengine version?

**Comment by chocstarfish** [comment]
I am using
```
 <dependency>
            <groupId>org.rythmengine</groupId>
            <artifactId>rythm-engine</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.ctlok</groupId>
            <artifactId>spring-webmvc-rythm</artifactId>
            <version>1.4.2</version>
        </dependency>
```

**Comment by greenlaw110** [comment]
try 1.1.1-SNAPSHOT and let me know the result

**Comment by greenlaw110** [comment]
I can't reproduce this issue on the latest version. I believe this issue is duplicated with issue #237 which has been fixed before
