### ISSUE TITLE
Reinit of Rythm

### ISSUE THREAD

**Issue by WolfgangFahl** [greenlaw110/Rythm#256]
my JUnit TestSuite for a project fails after adding the test

```
 @Test
  public void testCompact() {
     String template="no whitespace here\n" + 
         "@for (int i=0;i<2;i++) \n" + 
         "{  please keep the whitespace\n}" + 
         "\nno whitespace here\n"  ;
     Map<String, Object> conf = new HashMap<String, Object>();
     conf.put("codegen.compact.enabled",false);
     Rythm.init(conf);
     Map<String, Object> rootMap = new HashMap<String, Object>();
     String result=Rythm.render(template,rootMap);
     check("no whitespace here\n" + 
         "  please keep the whitespace\n" + 
         "  please keep the whitespace\n" + 
         "no whitespace here\n",result);
  }
```

for http://stackoverflow.com/questions/29376686/unexpected-whitespace-handling-in-rythm-removes-wanted-blanks

```
java.lang.IllegalStateException: Rythm is already initialized
	at org.rythmengine.Rythm.init(Rythm.java:96)
	at org.sidif.wiki.TestRythm.testCompact(TestRythm.java:78)
```
	
This is very suprising. Why shouldn't it be possible to call the static method multiple times? Now there is a need for a uninit method which is not mentioned in the exception ...

**Comment by greenlaw110** [comment]
Not at all. `Rythm.init` is supposed to be called only once per JVM lifecycle. It's a very heavy object which full bunch of dependencies including class loader and resource managers.  For testing purpose, if you want to isolate Rythm for each test, call `Rythm.shutdown()` before `Rythm.init()`.

Also in real application unless it's very simple one, don't use `Rythm.xxx` directly, instead, create your own `RythmEngine` instance and use it. See http://rythmengine.org/doc/developer_guide.md#singleton_or_not for more information
