### ISSUE TITLE
forward Class references

### ISSUE THREAD

**Issue by WolfgangFahl** [greenlaw110/Rythm#257]
```
@{
  class A {
     B b;
     public void A() {
        B b=new B(this);
     }
  }
  class B {
     A a;
     public void B(A pA) {
        this.a=pA;
     }
  }
}
```

does not work ...
`org.rythmengine.exception.CompileException: B cannot be resolved to a type`

This is a real pitty since it cripples the Java possibilities a lot.

**Comment by greenlaw110** [comment]
Well I don't expect this scenario, so does Java compiler. Basically if you have circular reference it suggest you must have something in common that could be extracted into a third class. Rythm can't help here...

**Comment by WolfgangFahl** [comment]
please do not close this issue. It's important and would be a showstopper for my projects if this is not supported.

**Comment by greenlaw110** [comment]
I have opened an new issue #264 to track the feature request

**Comment by WolfgangFahl** [comment]
264 is not what I asked for see #264
