### ISSUE TITLE
Allow template author to add arbitrary code at class level

### ISSUE THREAD

**Issue by greenlaw110** [greenlaw110/Rythm#271]
This is a feature request as per issue #267. The feature allows template author to put any code snippet into the class scope. For example the following code:

```
@def static {
class MyInnerClass {
    String foo() {
        return "hello foo";
    }
}
}

@{
MyInnerClass inst = new MyInnerClass();
}

@inst.foo()
```

Will generate:

```
hello foo
```

**Comment by WolfgangFahl** [comment]
Excellent work! This is a dream coming true. Code testing is now so much faster. The code is now truely portable between the rythm and java environments. I love this.

**Comment by greenlaw110** [comment]
glad that helps :-)
