### ISSUE TITLE
TemplateClassLoader does not implement ClassLoader#findClass(String)

### ISSUE THREAD

**Issue by jkcclemens** [greenlaw110/Rythm#272]
I have been hunting down a bug for a long time, and I finally found it. Rythm's TemplateClassLoader does not implement findClass(String), yet it implements loadClass(String). This causes issues in certain JVM states, causing it to appear as if the ClassLoader does not have access to some classes.

As stated by the ClassLoader Javadocs:
> This method should be overridden by class loader implementations that follow the delegation model for loading classes, and will be invoked by the loadClass method after checking the parent class loader for the requested class.

The default implementation always throws a ```ClassNotFoundException```.

This issue is preventing me from using Rythm in production, and I would really love to.

**Comment by greenlaw110** [comment]
Usually if you have your own specific classloader, you should pass that classloader to Rythm's class loader as a parent classloader, refer to https://github.com/actframework/actframework/blob/master/src/main/java/act/view/rythm/RythmView.java and https://github.com/greenlaw110/play-rythm/blob/master/src/org/rythmengine/play/RythmPlugin.java to see how the framework level class loader is passed to rythm's template classloader via `ENGINE_CLASS_LOADER_PARENT_IMPL` which is documented at http://rythmengine.org/doc/configuration.md#engine_class_loader_parent_impl

**Comment by jkcclemens** [comment]
I do this already. See [here](https://github.com/Chatterbox/Chatterbox/blob/master/modules/Chatterbox/src/main/java/works/chatterbox/chatterbox/api/rythm/RythmAPI.java#L31). The findClass(String) method still needs to be implemented, even with a parent class loader.

**Comment by greenlaw110** [comment]
Not a rythm issue. See https://github.com/Chatterbox/Chatterbox/issues/28
