### ISSUE TITLE
CompileException “annotations are only available if source level is 1.5 or greater”

### ISSUE THREAD

**Issue by lelandjc** [greenlaw110/Rythm#284]
I'm calling rythmengine with Java 1.8, compiled and executed via Gradle.

Here's the exception:

org.rythmengine.exception.CompileException: Syntax error, annotations are only available if source level is 1.5 or greater

Relevant Java source lines:

   2: import org.rythmengine.template.TemplateBase;
   3: import java.io.*;
   4: 
   5: public class C73bd49e7_ca2e_33dd_a822_07d30e7f8c26__R_T_C__ extends org.rythmengine.template.TagBase {
   6: 
>> 7:   @Override public java.lang.String __getName() {
   8:       return "C73bd49e7_ca2e_33dd_a822_07d30e7f8c26__R_T_C__";
   9:   }
   10: 
   11: 
   12:  protected java.lang.String __renderArgName(int __pos) {
   13:      int __p = 0;

Elsewhere in my code I'm using annotations without any trouble, and I've verified that Gradle really is running JRE 1.8. The problem seems to be happening with Rythm's internal compiler. 

I tried adding -Djava.version=1.8 to the command line when launching gradle, but the same thing still happens.

**Comment by greenlaw110** [comment]
What's your Rythm version?

**Comment by lelandjc** [comment]
1.1.1

**Comment by greenlaw110** [comment]
Can you please try 1.1.3-SNAPSHOT?

**Comment by lelandjc** [comment]
Where/how would I get 1.1.3-SNAPSHOT?

**Comment by greenlaw110** [comment]
use maven:

```
  <parent>
    <groupId>org.sonatype.oss</groupId>
    <artifactId>oss-parent</artifactId>
    <version>7</version>
  </parent>
...
  <dependencies>
    <dependency>
      <groupId>org.rythmengine</groupId>
      <artifactId>rythm-engine</artifactId>
      <version>1.1.3-SNAPSHOT</version>
    </dependency>
  </dependencies>

```

**Comment by greenlaw110** [comment]
@lelandjc does the new version fixed the issue?

**Comment by lelandjc** [comment]
No, same issue.

**Comment by greenlaw110** [comment]
Is it possible for you send out a simple project package that can reproduce the issue?

**Comment by lelandjc** [comment]
Unfortunately I can't spend time on it at this moment, but will see if I can come back to this later in the project. Also will update you if I'm able to isolate and/or solve the issue.

**Comment by mikedias** [comment]
I have the same issue here. I will prepare reproducible package soon.

**Comment by greenlaw110** [comment]
@mikedias appreciate that...

**Comment by mikedias** [comment]
I just realized that this problem only occurs when the war is deployed on a **Weblogic 12.2.1**. When I deploy the same war on a **Wildfly 8.2.0.Final**, the problem doesn't happen. @greenlaw110 Is that give you a clue?

**Comment by greenlaw110** [comment]
Is there any difference in Java version on the two environment?

**Comment by mikedias** [comment]
Both are running with **jdk1.8.0_45-b14** on Mac OS X El Captain.

**Comment by greenlaw110** [comment]
That's weird. I am not sure where is the problem. But I removed the "@Override" in the generated source code. Please try again with latest 1.1.4-SNAPSHOT

**Comment by greenlaw110** [comment]
Sorry I didn't realize my changes is not saved. Just updated the SNAPSHOT, please run mvn with "--update-snapshots" option to refresh the lib

**Comment by mikedias** [comment]
My usage:
```
String rawQuery = ...
Map<String, Object> params = ...

String render = Rythm.substitute(rawQuery, params);
```

New error:
```
org.rythmengine.exception.CompileException: Syntax error, parameterized types are only available if source level is 1.5

Template: g.V.has('key', '@currentUser').out('belongs_to').key

Relevant template source lines:
-------------------------------------------------
   1: g.V.has('key', '@currentUser').out('belongs_to').key


Relevant Java source lines:
-------------------------------------------------
   18: 		int __p = 0;
   19: 		if (__p++ == __pos) return "currentUser";
   20: 		throw new ArrayIndexOutOfBoundsException();
   21: 	}
   22: 
>> 23: 	protected java.util.Map<java.lang.String, java.lang.Class> __renderArgTypeMap() {
   24: 		java.util.Map<java.lang.String, java.lang.Class> __m = new java.util.HashMap<String, Class>();
   25: 		__m.put("currentUser", Object.class);
   26: 		return __m;
   27: 	}
   28: 
   29: 	@SuppressWarnings("unchecked")
```

**Comment by greenlaw110** [comment]
It looks like your environment is using a very old ECJ (Eclipse Compiler), can you check your classpath?

**Comment by greenlaw110** [comment]
I've built another 1.1.4-SNAPSHOT version with some log statements:

1. the java version setting
![image](https://cloud.githubusercontent.com/assets/216930/11855305/8d3c6ee4-a49d-11e5-8e66-df22f1f8e61f.png)

2. the jdt compiler option after set the java version
![image](https://cloud.githubusercontent.com/assets/216930/11855267/427cdbdc-a49d-11e5-8dac-2a2ff2db308e.png)

3. the jdt compiler option when error encountered:
![image](https://cloud.githubusercontent.com/assets/216930/11855286/660d4f28-a49d-11e5-9c92-8e2071783455.png)

Can you please try that and send out the corresponding log to help debug the issue?

**Comment by mikedias** [comment]
I'll verify my classpath. By now, here is the log:
```
##### Rythm Compiler Java Version is set to 1.8
##### JDK_1_1 = 2949123
##### JDK_1_2 = 3014656
##### JDK_1_3 = 3080192
##### JDK_1_4 = 3145728
##### JDK_1_5 = 3211264
##### JDK_1_6 = 3276800
##### JDK_1_7 = 3342336
##### JDK_1_8 = 3407872
##### compiler option source level: 3080192
##### compiler option target level: 3014656
##### compiler option compliance level: 3145728
>>>> compliance level: 3145728
>>>> source level: 3080192
>>>> target level: 3014656
```

**Comment by greenlaw110** [comment]
Interesting, your JVM setting on source, target and compliance are different. I've added two more lines to check the JVM version in `settings` and `options`:
![image](https://cloud.githubusercontent.com/assets/216930/11887390/d384c7ee-a587-11e5-8ffe-c3f2e16e31cc.png)

Please try with the new 1.1.4-SNAPSHOT version again. I just want to make sure something outside of Rythm changed the setting of ECJ

**Comment by mikedias** [comment]
I finally figure out what is happening. Thank you for your classpath tip.
I had a drools dependency that points to an old ECJ version:

```
+- org.drools:drools-compiler:jar:5.5.0.Final:compile
|  +- org.antlr:antlr-runtime:jar:3.3:compile
|  +- org.antlr:antlr:jar:3.3:compile
|  +- org.antlr:stringtemplate:jar:3.2.1:compile
|  +- antlr:antlr:jar:2.7.7:compile
|  \- org.eclipse.jdt.core.compiler:ecj:jar:3.5.1:compile
```

I updated my dependencyManagement to use a new version and the Rythm templates works fine now!
