### ISSUE TITLE
Support for disabling global JVM shutdown hook

### ISSUE THREAD

**Issue by JensRantil** [greenlaw110/Rythm#296]
**Background:** We previously ran into the issue of thread safety mentioned in #20. To accomodate for that, we started using an object pool of multiple `Rythm` instances. This worked great until I today discovered that `Rythm` automagically registers a global shutdown hook which automatically shuts down all `Rythm` instances before my own application is done with all the pooled objects. This means I occasionally get lots of exceptions on shutdown.

**Problem:** Looking in `RythmEngine#init` I see I can't disable registering to the shutdown hook.

**Proposed solution:** Avoid hardcoding in a shutdown hook. It should be called outside of this library to give allow the user decide when to shut down Rythm.

**Workaround:** AFAIK, none.

**Comment by JensRantil** [comment]
Somewhat related, http://rythmengine.org/doc/developer_guide.md#singleton_or_not clearly isn't singleton since there is a global/singleton shutdown hook involved.

**Comment by greenlaw110** [comment]
Thanks for the issue report. I've moved out the relevant code from `RythmEngine` to `Rythm`

**Comment by JensRantil** [comment]
Thanks @greenlaw110! Would it be possible for you to publish a new release with the patch?

**Comment by greenlaw110** [comment]
Yes I will. Before the release version come out, please use 1.1.4-SNAPSHOT

**Comment by JensRantil** [comment]
Any progress on making a new release? Looks like someone asked for it in #295, too?
